# Generated by Django 3.2 on 2025-05-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_sensordata_dht'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensor_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'sensor_data',
                'managed': False,
            },
        ),
    ]
