# Generated by Django 3.2 on 2025-05-08 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sensor_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor_data',
            options={},
        ),
    ]
