# Generated by Django 3.2 on 2025-05-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_sensor_data_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor_data',
            options={'managed': False},
        ),
    ]
